function R = EUL_ZYX_to_R_wb(eul)
rotx = [1 0 0;...
        0 cos(eul(1)) -sin(eul(1));...
        0 sin(eul(1)) cos(eul(1))];
roty = [cos(eul(2)) 0 sin(eul(2));...
        0 1 0;...
        -sin(eul(2)) 0 cos(eul(2))];
rotz = [cos(eul(3)) -sin(eul(3)) 0;...
        sin(eul(3)) cos(eul(3)) 0;...
        0 0 1];
R = (rotz*roty*rotx)';